# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'cocoapods' do

end

target 'cocoapodsTests' do

end

platform :ios, '6.0'
pod 'AFNetworking', '1.3.0'
#pod 'JSONKit', '~> 1.5pre'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'RestKit', '~> 0.23.3'
#pod 'Reachability', '~> 3.1.1'
#pod 'UI7Kit', '~> 0.9.18'
#pod 'RegexKitLite', '~> 4.0'
#pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
#pod 'MBProgressHUD', '~> 0.9'
#pod 'SVPullToRefresh', '~> 0.4.1'
#pod 'LKbadgeView', '~> 1.1.0'
#pod 'PPiFlatSegmentedControl', '~> 1.3.8'